-- 코드를 입력하세요
WITH INFO AS (SELECT BOOK_ID, SUM(SALES) AS SALES
             FROM BOOK_SALES
             WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
             GROUP BY BOOK_ID)
             
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((B.PRICE * I.SALES)) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN INFO I ON B.BOOK_ID = I.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC

# SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES