WITH INFO AS (
    SELECT BOOK_ID, SUM(SALES) as SALES
    FROM BOOK_SALES 
    WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
    GROUP BY BOOK_ID
)

SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, CATEGORY, SUM(SALES * BOOK.PRICE) as TOTAL_SALES
FROM BOOK
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN INFO ON BOOK.BOOK_ID = INFO.BOOK_ID
GROUP BY AUTHOR.AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
