-- 2022년 3월의 온라인 판매 데이터를 조회
SELECT 
  DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
  PRODUCT_ID, 
  USER_ID, 
  SALES_AMOUNT
FROM 
  ONLINE_SALE
WHERE 
  YEAR(SALES_DATE) = 2022 
  AND MONTH(SALES_DATE) = 3

UNION ALL

-- 2022년 3월의 오프라인 판매 데이터를 조회하고 USER_ID를 NULL로 설정
SELECT 
  DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
  PRODUCT_ID, 
  NULL AS USER_ID, 
  SALES_AMOUNT
FROM 
  OFFLINE_SALE
WHERE 
  YEAR(SALES_DATE) = 2022 
  AND MONTH(SALES_DATE) = 3

ORDER BY 
  SALES_DATE ASC, 
  PRODUCT_ID ASC, 
  USER_ID ASC;
