WITH ANSWER AS (
    SELECT AI.ANIMAL_ID, AI.NAME, DATEDIFF(AO.DATETIME, AI.DATETIME) as DATETIME
    FROM ANIMAL_INS AI
    JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
    ORDER BY 3 DESC
    LIMIT 2
)



SELECT ANIMAL_ID, NAME
FROM ANSWER
