WITH FOOD AS (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
             FROM REST_INFO
             GROUP BY FOOD_TYPE)
             
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI
JOIN FOOD ON RI.FOOD_TYPE = FOOD.FOOD_TYPE AND RI.FAVORITES = FOOD.FAVORITES
ORDER BY FOOD_TYPE DESC
