SELECT ii.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO as ii
JOIN ITEM_TREE as it ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ii.ITEM_ID DESC;
