WITH TEMP AS (
    SELECT CAR_ID, COUNT(*) as CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)
             
SELECT MONTH(START_DATE) AS MONTH, CAR.CAR_ID, COUNT(CAR.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CAR
JOIN TEMP ON CAR.CAR_ID = TEMP.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(START_DATE), CAR.CAR_ID
ORDER BY MONTH(START_DATE) ASC, CAR.CAR_ID DESC;