WITH CAR_RENTAL_COUNT AS (
    -- 대여 시작일을 기준으로 2022-08 ~ 2022-10 기간 동안 자동차별 총 대여 횟수 계산
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08'
      AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

-- 월별 자동차 ID별 총 대여 횟수 계산 및 정렬
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08'
  AND DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10'
  AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COUNT)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;
