WITH AVGINFO AS (SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG
                FROM HR_EMPLOYEES
                GROUP BY DEPT_ID)

SELECT HD.DEPT_ID, DEPT_NAME_EN, AVG AS AVG_SAL
FROM HR_DEPARTMENT HD
JOIN AVGINFO I ON HD.DEPT_ID = I.DEPT_ID
ORDER BY AVG_SAL DESC
