-- 코드를 입력하세요
WITH TEMP AS (SELECT CATEGORY, MAX(PRICE) as PRICE
             FROM FOOD_PRODUCT
             GROUP BY CATEGORY)

SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
JOIN TEMP ON FP.CATEGORY = TEMP.CATEGORY AND FP.PRICE = TEMP.PRICE
WHERE FP.CATEGORY IN ( '과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
