WITH LEN AS (SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
               FROM FISH_INFO),
    INFO AS (SELECT FISH_TYPE, AVG(LEN.LENGTH) AS AVG, MAX(LEN.LENGTH) AS MAX, COUNT(FISH_TYPE) AS COUNT
            FROM LEN
            GROUP BY FISH_TYPE)

             
SELECT INFO.COUNT AS FISH_COUNT, INFO.MAX AS MAX_LENGTH, INFO.FISH_TYPE
FROM INFO
WHERE INFO.AVG >= 33
ORDER BY FISH_TYPE